create or replace view entity_weekly_rollup_v as
select date_trunc('week', date)::date as week_start,
       entity_type,
       entity_id,
       company_id,
       ceo_id,
       entity_name,
       company,
       ceo,
       sum(article_negative_count) as article_negative_7d,
       sum(article_total_count) as article_total_7d,
       avg(article_negative_pct) as article_negative_pct_avg_7d,
       sum(serp_negative_count) as serp_negative_7d,
       sum(serp_total_count) as serp_total_7d,
       sum(serp_controlled_count) as serp_controlled_7d,
       sum(serp_uncontrolled_count) as serp_uncontrolled_7d,
       sum(top_stories_total_count) as top_stories_total_7d,
       sum(top_stories_negative_count) as top_stories_negative_7d,
       sum(top_stories_controlled_count) as top_stories_controlled_7d,
       sum(top_stories_uncontrolled_count) as top_stories_uncontrolled_7d,
       count(*) filter (where top_stories_negative_count >= 4) as top_stories_crisis_days_7d,
       sum(crisis_risk_count) as crisis_risk_7d
from entity_daily_metrics_v
group by date_trunc('week', date)::date,
         entity_type,
         entity_id,
         company_id,
         ceo_id,
         entity_name,
         company,
         ceo;
